let a = ("<h1>Hellow World!</h1>")
document.write(a)
let b =("<p>Habe a nica day!</p>")
document.write(b)
let myText = ("Hello again <br>")
document.write(myText)
let vorname = ("Dilman ")
let nachname = ("Namdar")
document.write(vorname , nachname)